spring:
  application:
    name: observability-api

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring:application:name}
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
